### ISSUE TITLE
Basis functions on the right side get evaluated to zero

### ISSUE THREAD

**Issue by henrij22** [HoBeZwe/NURBS.jl#9]
Hi, thanks for the package!

I noticed that when using the `evalNaive` functions all basis functions get evaluated to zero at the right side of the knot vector (i.e. exactly 1.0). If you evaluate at `u = 0.9999` you get a sensible result. Or is this the inteded result?

Minimal working example (Julia v1.10)

```jl
using NURBS

p = 1
n = 2
knots = NURBS.generateKnotVec(n, p)

basis = Bspline(p, knots)

evalNaive(basis, 1, 0.0) ≈ 1.0 # true
evalNaive(basis, 1, 1.0) ≈ 0.0 # true

evalNaive(basis, 2, 0.0) ≈ 0.0 # true
evalNaive(basis, 2, 1.0) ≈ 1.0 # false

evalNaive(basis, 2, 1.0) == 0.0 # true
evalNaive(basis, 2, 0.9999) ≈ 0.9999 # true
```

**Comment by HoBeZwe** [comment]
Hi, good point you are bringing up.

In principle, `evalNaive` till now precisely was following the [definition](https://hobezwe.github.io/NURBS.jl/dev/basis_def/#bspl), which is based on half-open intervals.

However, it is common to set the rightmost basis function to 1 at the point 1, to maintain the partition of unity property.

Since this is already done so for the more efficient evaluation, I've adapted the naive evaluation and updated the documentation accordingly.

Hence, `evalNaive` behaves in the new release now as you expected in the first place:

```jl
using NURBS

p = 1
n = 2
knots = NURBS.generateKnotVec(n, p)

basis = Bspline(p, knots)

evalNaive(basis, 1, 0.0) ≈ 1.0 # true
evalNaive(basis, 1, 1.0) ≈ 0.0 # true

evalNaive(basis, 2, 0.0) ≈ 0.0 # true
evalNaive(basis, 2, 1.0) ≈ 1.0 # true

evalNaive(basis, 2, 1.0) == 0.0 # false
evalNaive(basis, 2, 0.9999) ≈ 0.9999 # true
```

**Comment by henrij22** [comment]
Hi, 
thanks for adressing my issue. 
And also thanks for pointing out the actual definition. I wasn't aware of that. 

But I think from a computational standpoint I think its better and more reasonable this way
